# Generated by Django 3.2.13 on 2022-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='main/image/')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['pub_date'],
            },
        ),
    ]
