# Generated by Django 3.2.13 on 2022-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220714_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='Cities',
        ),
        migrations.AddField(
            model_name='blog',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
