# Generated by Django 3.2.13 on 2022-07-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='lan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cities',
            name='lat',
            field=models.FloatField(default=0),
        ),
    ]
