# Generated by Django 3.2.13 on 2022-07-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220730_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='lan',
            new_name='lon',
        ),
    ]
