# Generated by Django 3.2.13 on 2022-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200, verbose_name='App name')),
                ('url', models.URLField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='url')),
                ('summary', models.TextField(max_length=400)),
                ('image_url', models.URLField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'App name',
                'verbose_name_plural': 'Apps names',
            },
        ),
    ]
