# Generated by Django 3.2.13 on 2022-07-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapps',
            name='image_url',
            field=models.URLField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='image_url'),
        ),
    ]
