# Generated by Django 3.2.13 on 2022-07-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_myapps_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapps',
            name='url',
        ),
        migrations.AddField(
            model_name='myapps',
            name='url_str',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='url string'),
        ),
    ]
