# Generated by Django 3.2.13 on 2022-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220715_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapps',
            name='image_url',
        ),
        migrations.AddField(
            model_name='myapps',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='myapps',
            name='url_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='url string'),
        ),
    ]
