# Generated by Django 3.2.13 on 2022-08-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220802_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapps',
            name='url_str',
        ),
    ]
