# Generated by Django 3.2.13 on 2022-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=300, verbose_name='Task')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['deadline'],
            },
        ),
    ]
