# Generated by Django 3.2.13 on 2022-06-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline_day', 'deadline_time'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_day',
            field=models.DateField(null=True, verbose_name='Deadline_day'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.DateField(null=True, verbose_name='Deadline_time'),
        ),
    ]
