# Generated by Django 3.2.13 on 2022-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0002_auto_20220625_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(null=True, verbose_name='Deadline_time'),
        ),
    ]
