# Generated by Django 3.2.13 on 2022-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
