# Generated by Django 3.2.13 on 2022-08-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='skill',
            name='url',
            field=models.URLField(db_index=True, max_length=100, null=True, unique=True, verbose_name='url'),
        ),
    ]
