# Generated by Django 3.2.13 on 2022-08-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220802_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='url',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
