# Generated by Django 3.2.13 on 2022-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220802_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='skill_icon'),
        ),
    ]
