# Generated by Django 3.2.13 on 2022-06-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('sub_category', models.CharField(max_length=50, verbose_name='subcategory')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('context', models.TextField(max_length=300, verbose_name='context')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='links.categories')),
            ],
            options={
                'verbose_name': 'Link to a certain website',
                'verbose_name_plural': 'Links to a certain websites',
                'ordering': ['sub_category', 'title'],
            },
        ),
    ]
