# Generated by Django 3.2.13 on 2022-06-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='slug',
        ),
        migrations.AddField(
            model_name='links',
            name='url',
            field=models.URLField(db_index=True, max_length=255, null=True, unique=True, verbose_name='url'),
        ),
    ]
