# Generated by Django 3.2.13 on 2022-06-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20220622_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(max_length=33, verbose_name='title'),
        ),
    ]
